"use strict";
const assert = require("assert"); const C = require("../src/ai-3d/core.js"); const R = require("../src/ai-3d/rlm/rlm-core.js");
class Storage { getItem() { return null; } setItem() {} }
const manager = new C.ConversationTaskManager({ storage: new Storage() }); const registry = new R.RlmToolRegistry();
registry.register({ name: "inventory_search", capability: "STOCK.SEARCH", description: "estoque", inputSchema: {}, outputSchema: {}, access: "READ", requiresConfirmation: false, riskLevel: "READ", execute: async () => ({ status: "SUCCESS", items: [{ name: "PETG preto", quantity: 2 }] }) });
registry.register({ name: "orders_search", capability: "ORDER.HISTORY", description: "pedidos", inputSchema: {}, outputSchema: {}, access: "READ", requiresConfirmation: false, riskLevel: "READ", execute: async () => ({ status: "SUCCESS", orders: [] }) });
registry.register({ name: "production_summary", capability: "PRODUCTION.SEARCH", description: "produção", inputSchema: {}, outputSchema: {}, access: "READ", requiresConfirmation: false, riskLevel: "READ", execute: async () => ({ status: "SUCCESS", total: 1 }) });
registry.register({ name: "pricing_calculate", capability: "PRICE.CALCULATE", description: "preço", inputSchema: {}, outputSchema: {}, access: "READ", requiresConfirmation: false, riskLevel: "READ", execute: async () => ({ status: "SUCCESS", value: 4 }) });
registry.register({ name: "customers_search", capability: "CUSTOMER.SEARCH", description: "cliente", inputSchema: {}, outputSchema: {}, access: "READ", requiresConfirmation: false, riskLevel: "READ", execute: async ({ query }) => ({ status: "SUCCESS", customer: { name: query } }) });
registry.register({ name: "draft_order_create", capability: "ORDER.DRAFT", description: "draft", inputSchema: {}, outputSchema: {}, access: "DRAFT", requiresConfirmation: false, riskLevel: "DRAFT", execute: async (input) => { manager.startOrder({ customer: input.customer, product: input.product, quantity: input.quantity }); return { status: "SUCCESS" }; } });
const rlm = new R.RlmOrchestrator({ registry, manager });
(async()=>{ assert.strictEqual(rlm.classify("confirmar"), R.ROUTE.FAST_PATH); assert.strictEqual(rlm.classify("Quanto tenho de PETG preto?"), R.ROUTE.SIMPLE_TOOL); let result=await rlm.run("Tenho material suficiente para os pedidos de amanhã?"); assert.strictEqual(result.route,R.ROUTE.RLM); assert(result.toolsCalled.length<=5); result=await rlm.run("Crie um pedido de 100 chaveiros para Natali."); assert.strictEqual(result.createdDraft,true); assert.strictEqual(manager.session.activeDraft.items[0].quantidade.value,100); assert.strictEqual(manager.session.pendingAction,null); console.log("RLM: rotas, limites, retrieval, evidência e Draft validados."); })().catch(e=>{console.error(e);process.exitCode=1});
