create table if not exists public.email_broadcasts (
  id uuid primary key default gen_random_uuid(),
  created_by uuid not null default auth.uid() references auth.users(id) on delete restrict,
  subject text not null check (char_length(subject) between 3 and 160),
  message text not null check (char_length(message) between 10 and 10000),
  audience jsonb not null default '{"status":"active","plan":"all"}'::jsonb,
  status text not null default 'draft' check (status in ('draft','processing','sent','partial','failed')),
  recipient_count integer not null default 0,
  sent_count integer not null default 0,
  failed_count integer not null default 0,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz
);

create table if not exists public.email_broadcast_recipients (
  id bigint generated by default as identity primary key,
  broadcast_id uuid not null references public.email_broadcasts(id) on delete cascade,
  client_id uuid references public.clients(id) on delete set null,
  email text not null,
  client_name text,
  status text not null default 'pending' check (status in ('pending','sent','failed','skipped')),
  provider_message_id text,
  error_message text,
  sent_at timestamptz,
  unique (broadcast_id, email)
);

create index if not exists email_broadcasts_created_idx on public.email_broadcasts(created_at desc);
create index if not exists email_broadcast_recipients_status_idx on public.email_broadcast_recipients(broadcast_id, status);

alter table public.email_broadcasts enable row level security;
alter table public.email_broadcast_recipients enable row level security;
revoke all on public.email_broadcasts, public.email_broadcast_recipients from anon;
grant select, insert, update on public.email_broadcasts to authenticated;
grant select on public.email_broadcast_recipients to authenticated;

drop policy if exists "email_broadcasts_superadmin_all" on public.email_broadcasts;
create policy "email_broadcasts_superadmin_all" on public.email_broadcasts
for all to authenticated using (public.erp_is_superadmin()) with check (public.erp_is_superadmin());
drop policy if exists "email_broadcast_recipients_superadmin_select" on public.email_broadcast_recipients;
create policy "email_broadcast_recipients_superadmin_select" on public.email_broadcast_recipients
for select to authenticated using (public.erp_is_superadmin());
