(function initUiV3Overlays(global){
  let active=null;let opener=null;
  const focusable='button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])';
  function close(){if(!active)return;const root=active.closest('[data-ui-version="v3"]');active.remove();active=null;root?.classList.remove('ui3-overlay-open');document.removeEventListener('keydown',onKeydown,true);opener?.focus?.();opener=null;}
  function onKeydown(event){if(event.key==='Escape'){event.preventDefault();close();return}if(event.key!=='Tab'||!active)return;const nodes=[...active.querySelectorAll(focusable)].filter(node=>!node.disabled);if(!nodes.length)return;const first=nodes[0],last=nodes.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
  function open({kind='dialog',title='Janela',content='',fullscreen=false}){close();const root=document.querySelector('[data-ui-version="v3"]');if(!root)return;opener=document.activeElement;const portal=document.createElement('div');portal.className=`ui3-portal ui3-${kind}-portal`;portal.dataset.ui3Portal=kind;const panelClass=fullscreen?'ui3-dialog ui3-fullscreen':`ui3-${kind}`;portal.innerHTML=`<section class="${panelClass}" role="dialog" aria-modal="true" aria-labelledby="ui3-overlay-title"><div class="ui3-stack"><div class="ui3-page-header"><h2 id="ui3-overlay-title">${title}</h2><button class="ui3-button" data-variant="secondary" data-ui3-close>Fechar</button></div>${content}</div></section>`;portal.addEventListener('pointerdown',event=>{if(event.target===portal)close()});portal.querySelector('[data-ui3-close]').addEventListener('click',close);root.append(portal);root.classList.add('ui3-overlay-open');active=portal;document.addEventListener('keydown',onKeydown,true);queueMicrotask(()=>portal.querySelector(focusable)?.focus());history.pushState({ui3Overlay:true},'',location.href);return portal}
  addEventListener('popstate',()=>{if(active)close()});
  global.UiV3=Object.assign(global.UiV3||{},{Dialog:(options)=>open({...options,kind:'dialog'}),BottomSheet:(options)=>open({...options,kind:'sheet'}),Drawer:(options)=>open({...options,kind:'drawer'}),ConfirmationDialog:({title='Confirmar',message})=>open({kind:'dialog',title,content:`<p>${message}</p><div class="ui3-sticky-actions"><button class="ui3-button" data-variant="danger" data-ui3-close>Confirmar</button></div>`}),closeOverlay:close});
})(window);
